### PR TITLE
pretty++

### PR DESCRIPTION
**Pull request by burnoutberni**

### CODE REVIEW

**Comment by phaer** [comment]
Looks good, thanks! I am not sure about the use of Unicode symbols for search and so on, especially regarding their accessibility for users with older fonts and/or visual impairment. It's not really a problem in Panamas current state, but wouldn't svg/png icons with an alternative text still be the better option?

**Comment by phaer** [comment]
Ah, max-width for the container would be nice and at the moment, the volume control disappears if the window becomes too narrow. Is this intended to be the final color scheme?

**Comment by burnoutberni** [comment]
Regarding
* Unicode symbols: Yes, to be replaced by svg icons, but requires a bit of refactoring of the slider class.
* max-width: Not sure, I like the fullscreen-y version, but I'm also fine with a max-width. What background would you suggest then though?
* volume control: I'll look at it.
* color scheme: Nope, but I guess it's okay like that. Maybe pick a prettier red.

**Comment by burnoutberni** [comment]
- [ ] Unicode symbols
- [x] max-width
- [x] stretching issues with sliders and such
- [ ] color scheme

@phaer, Feedback?

**Pull request merged**
